USE [master]
GO

CREATE LOGIN [Kevin] WITH PASSWORD=N'Kevin=', DEFAULT_DATABASE=[Orders], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

USE [Orders]
GO

CREATE USER [Kevin] FOR LOGIN [Kevin] WITH DEFAULT_SCHEMA=[dbo]
GO


