//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenesisModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OrdersEntities : DbContext
    {
        public OrdersEntities()
            : base("name=OrdersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
    
        public virtual ObjectResult<spr_SelectAllOrdersWithCustomers_Result> spr_SelectAllOrdersWithCustomers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_SelectAllOrdersWithCustomers_Result>("spr_SelectAllOrdersWithCustomers");
        }
    
        public virtual ObjectResult<spr_SelectAllOrdersWithCustomers_Result> SelectAllOrdersWithCustomers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spr_SelectAllOrdersWithCustomers_Result>("SelectAllOrdersWithCustomers");
        }
    }
}
